import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import Image from 'next/image'

interface PatientRegistrationPageProps {
  params: Promise<{
    'qr-code': string
  }>
}

export default async function PatientRegistrationPage({ params }: PatientRegistrationPageProps) {
  const resolvedParams = await params
  const qrCode = resolvedParams['qr-code']

  return (
    <div className="min-h-screen bg-background flex items-center justify-center p-4">
      <div className="w-full max-w-2xl">
        <Card className="border-0 shadow-2xl">
          <CardHeader className="text-center space-y-4 pb-6">
            <div className="flex justify-center">
              <div className="bg-primary/10 p-4 rounded-2xl border border-primary/20 relative shadow-lg">
                <Image
                  src="/lav-dentaire-logo.svg"
                  alt="LAV Dentaire Logo"
                  width={40}
                  height={40}
                  className="h-10 w-10"
                />
                <div className="absolute -top-1 -right-1 bg-primary h-3 w-3 rounded-full border-2 border-background animate-pulse" title="System Online" />
              </div>
            </div>
            <div className="space-y-1">
              <CardTitle className="text-lg font-semibold">Patient Registration</CardTitle>
              <CardDescription className="text-sm">
                LAV Dentaire - New Patient Information
              </CardDescription>
            </div>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="text-center p-8">
              <p className="text-muted-foreground mb-4">
                QR Code: <code className="bg-muted px-2 py-1 rounded">{qrCode}</code>
              </p>
              <p className="text-lg text-muted-foreground">
                Patient registration form will be implemented in Phase 6
              </p>
              <p className="text-sm text-muted-foreground mt-2">
                This page will allow patients to self-register using QR codes generated by the admin
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}